version: "3.2"
services:
  frontend:
      image: varshakirani/frontvar
      deploy:
         replicas: 2
         placement:
              constraints:
                  - node.hostname == ${LC_STACKNAME}-frontend
         restart_policy:
              condition: on-failure
      volumes:
         - /etc:/hypervisor_etc
      ports:
         - "80:80"
      environment:
         - CC_BACKEND_SERVERS=${LC_BACKEND_IPS}

