heat_template_version: 2015-10-15
description: One VM instance

#openstack stack create -t server.yaml  --parameter name=serverInstance2 --parameter key_name=newKey --parameter flavor="Cloud Computing" --parameter  image=ubuntu-16.04 --parameter network=cc17-net --parameter zone="Cloud Computing 2017" --parameter security_groups=default stack1
parameters:
    name:
        type: string
        label: Name of the VM
    key_name:
        type: string
        label: Key Pair
        constraints:
            - custom_constraint: nova.keypair
    flavor:
        type: string
        label: Flavor
        constraints:
            - custom_constraint: nova.flavor
    image:
        type: string
        label: Image Name
        constraints:
            - custom_constraint: glance.image
    network:
        type: string
        label: Network
        constraints:
            - custom_constraint: neutron.network
    zone:
        type: string
        label: Availability Zone
        default: Default
    security_groups:
        type: comma_delimited_list
        label: Security Group(s)
        default: "default"
    subnetID:
        type: string
        label: subnet ID 

resources:

    # This port is a separate resource used to assign the security groups
    # to the VM. Can also be used to attach a OS::Neutron::FloatingIP to the VM.
    port:
        type: OS::Neutron::Port
        properties:
            network: { get_param: network }
            fixed_ips:
                - subnet_id: { get_param: subnetID }
            name:
                str_replace:
                    template: port-VM_NAME
                    params:
                        VM_NAME: { get_param: name }
            security_groups:
                get_param: security_groups
    
    instance:
        type: OS::Nova::Server
        properties:
            name: { get_param: name }
            key_name: { get_param: key_name }
            image: { get_param: image }
            flavor: { get_param: flavor }
            availability_zone: { get_param: zone }
            networks:
                - port: { get_resource: port }

outputs:
    ip:
        description: Virtual IP address of instance
        value: { get_attr: [ instance, first_address ] }
    port:
        description: Port ID of instance
        value: { get_resource: port }
