version: "3.2"
services:
  frontend:
      image: varshakirani/backend
      deploy:
         replicas: 5
         placement:
              constraints:
                  - node.hostname != ser-frontend
         restart_policy:
              condition: on-failure
      volumes:
         - /etc:/hypervisor_etc
      ports:
         - "80:8000"
