version: "3.2"
services:
  backend:
      image: varshakirani/backh
      deploy:
         replicas: 5
         placement:
              constraints:
                  - node.hostname != ${LC_STACKNAME}-frontend
         restart_policy:
              condition: on-failure
      volumes:
         - /etc:/hypervisor_etc
      ports:
         - "8000:80"
